name: Turkish Football Highlights Scraper

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  scrape_highlights:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          
      - name: Create Output Directory
        run: mkdir -p playsport
        
      - name: Run Scraper
        run: python ozetler.py
        
      - name: Verify Output Files
        run: |
          ls -la playsport/
          find playsport/ -name "*.m3u" | wc -l
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: football-highlights
          path: playsport/
