name: Download M3U Files

on:
  schedule:
    - cron: "0 */6 * * *"  # Her 6 saatte bir çalışır
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Repo'yu klonla
        uses: actions/checkout@v3

      - name: M3U dosyalarını indir
        run: |
          mkdir -p m3u
          cd m3u
          curl -O https://raw.githubusercontent.com/mehmetey03/metvvd/refs/heads/main/dizifun.m3u
          curl -O https://raw.githubusercontent.com/mehmetey03/metvvd/refs/heads/main/filmfun.m3u
          curl -O https://raw.githubusercontent.com/mehmetey03/metvvd/refs/heads/main/filmler.m3u
          curl -O https://raw.githubusercontent.com/mehmetey03/alma/refs/heads/main/m3u/Blutv.m3u
          curl -o Amazon_Prime.m3u https://raw.githubusercontent.com/mehmetey03/alma/refs/heads/main/m3u/Amazon%20Prime.m3u
          curl -O https://raw.githubusercontent.com/mehmetey03/alma/refs/heads/main/m3u/Netflix.m3u
          curl -o TOD_TV.m3u https://raw.githubusercontent.com/mehmetey03/alma/refs/heads/main/m3u/TOD%20TV.m3u
          curl -O https://raw.githubusercontent.com/mehmetey03/alma/refs/heads/main/m3u/Tabii.m3u
          curl -o HBO_Max.m3u https://raw.githubusercontent.com/mehmetey03/alma/refs/heads/main/m3u/HBO%20Max.m3u
          curl -O https://raw.githubusercontent.com/mehmetey03/alma/refs/heads/main/m3u/Hulu.m3u
          curl -O https://raw.githubusercontent.com/mehmetey03/METV/refs/heads/main/justsporthd1.m3u
          curl -O https://raw.githubusercontent.com/mehmetey03/xyzvtt/refs/heads/main/xyzvt.m3u
          curl -O https://raw.githubusercontent.com/mehmetey03/METV/refs/heads/main/salamistv1.m3u
          curl -O https://raw.githubusercontent.com/ahmet21ahmet/Atv/refs/heads/main/playsport/Trendyol_1._Lig_2025-2026/Trendyol_1._Lig_2025-2026.m3u
          curl -O https://raw.githubusercontent.com/ahmet21ahmet/Atv/refs/heads/main/playsport/S%C3%BCper_Lig_2025-2026/S%C3%BCper_Lig_2025-2026.m3u

      - name: Değişiklikleri commit'le
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add m3u/*.m3u
          git commit -m "M3U dosyaları güncellendi"
          git push
