name: Metv Sports Scraper

on:
  schedule:
    - cron: "*/15 * * * *"   # Her 15 dakikada bir çalışır
  workflow_dispatch:         # Manuel çalıştırma için

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run script
        run: python metv.py  # Script yolu, repo yapına göre düzenle

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: metv-outputs
          path: playsport/
          if-no-files-found: ignore
